-- Orphan/Micro uiMapID Fix
MapIDfix = {

	micro = {
	[ 2 ] 	= 1, -- Burning Blade Coven 	Micro 	Durotar
	[ 3 ] 	= 1, -- Tiragarde Keep 	Micro 	Durotar
	[ 4 ] 	= 1, -- Tiragarde Keep - Great Hall 	Micro 	Durotar
	[ 5 ] 	= 1, -- Skull Rock 	Micro 	Durotar
	[ 6 ] 	= 1, -- Dustwind Cave 	Micro 	Durotar
	[ 8 ] 	= 7, -- Palemane Rock 	Micro 	Mulgore
	[ 9 ] 	= 7, -- The Venture Co. Mine 	Micro 	Mulgore
	[ 11 ] 	= 10, -- Wailing Caverns 	Micro 	Northern Barrens
	[ 16 ] 	= 15, -- Uldaman 	Micro 	Badlands
	[ 19 ] 	= 18, -- Scarlet Monastery Entrance 	Micro 	Tirisfal Glades
	[ 20 ] 	= 18, -- Keeper's Rest 	Micro 	Tirisfal Glades
	[ 24 ] 	= 23, -- Light's Hope Chapel 	Micro 	Eastern Plaguelands
	[ 28 ] 	= 27, -- Coldridge Pass 	Micro 	Dun Morogh
	[ 29 ] 	= 27, -- The Grizzled Den 	Micro 	Dun Morogh
	[ 30 ] 	= 27, -- New Tinkertown 	Micro 	Dun Morogh
	[ 31 ] 	= 27, -- Gol'Bolar Quarry 	Micro 	Dun Morogh
	[ 33 ] 	= 36, -- Blackrock Mountain - Blackrock Spire 	Micro 	Burning Steppes
	[ 34 ] 	= 36, -- Blackrock Mountain - Blackrock Caverns 	Micro 	Burning Steppes
	[ 35 ] 	= 32, -- Blackrock Mountain - Blackrock Depths 	Micro 	Searing Gorge
	[ 38 ] 	= 37, -- Fargodeep Mine 	Micro 	Elwynn Forest
	[ 39 ] 	= 37, -- Fargodeep Mine - Lower Mines 	Micro 	Elwynn Forest
	[ 40 ] 	= 37, -- Jasperlode Mine 	Micro 	Elwynn Forest
	[ 41 ] 	= 42, -- Dalaran 	Micro 	Deadwind Pass
	[ 43 ] 	= 42, -- The Master's Cellar 	Micro 	Deadwind Pass
	[ 44 ] 	= 42, -- The Master's Cellar 	Micro 	Deadwind Pass
	[ 45 ] 	= 42, -- The Master's Cellar - Lower Cellar 	Micro 	Deadwind Pass
	[ 46 ] 	= 42, -- Karazhan Catacombs 	Micro 	Deadwind Pass
	[ 53 ] 	= 52, -- Gold Coast Quarry 	Micro 	Westfall
	[ 54 ] 	= 52, -- Jangolode Mine 	Micro 	Westfall
	[ 55 ] 	= 52, -- The Deadmines 	Micro 	Westfall
	[ 58 ] 	= 57, -- Shadowthread Cave 	Micro 	Teldrassil
	[ 59 ] 	= 57, -- Fel Rock 	Micro 	Teldrassil
	[ 60 ] 	= 57, -- Ban'ethil Barrow Den - Upper Den 	Micro 	Teldrassil
	[ 61 ] 	= 57, -- Ban'ethil Barrow Den - Lower Den 	Micro 	Teldrassil
	[ 67 ] 	= 66, -- Maraudon - The Wicked Grotto 	Micro 	Desolace
	[ 68 ] 	= 66, -- Maraudon - Foulspore Cavern 	Micro 	Desolace
	[ 72 ] 	= 71, -- The Noxious Lair 	Micro 	Tanaris
	[ 73 ] 	= 71, -- The Gaping Chasm 	Micro 	Tanaris
	[ 74 ] 	= 71, -- Caverns of Time - Timeless Tunnel 	Micro 	Tanaris
	[ 75 ] 	= 71, -- Caverns of Time 	Micro 	Tanaris
	[ 79 ] 	= 78, -- The Slithering Scar 	Micro 	Un'Goro Crater
	[ 82 ] 	= 81, -- Twilight's Run 	Micro 	Silithus
	[ 96 ] 	= 95, -- Amani Catacombs 	Micro 	Ghostlands
	[ 98 ] 	= 97, -- Tides' Hollow 	Micro 	Azuremyst Isle
	[ 99 ] 	= 97, -- Stillpine Hold 	Micro 	Azuremyst Isle
	[ 175 ] 	= 174, -- Kaja'mite Cavern 	Micro 	The Lost Isles
	[ 176 ] 	= 174, -- Volcanoth's Lair 	Micro 	The Lost Isles
	[ 177 ] 	= 174, -- Gallywix Labor Mine - Mine Tunnels 	Micro 	The Lost Isles
	[ 178 ] 	= 174, -- Gallywix Labor Mine - Mine Shaft 	Micro 	The Lost Isles
	[ 180 ] 	= 179, -- Emberstone Mine 	Micro 	Gilneas
	[ 181 ] 	= 179, -- Greymane Manor - Main Floor 	Micro 	Gilneas
	[ 182 ] 	= 179, -- Greymane Manor - Upper Floor 	Micro 	Gilneas
	[ 195 ] 	= 194, -- Kaja'mine 	Micro 	Kezan
	[ 196 ] 	= 194, -- Kaja'mine 	Micro 	Kezan
	[ 197 ] 	= 194, -- Kaja'mine 	Micro 	Kezan
	[ 208 ] 	= 207, -- Twilight Depths - Floor 1 	Micro 	Deepholm
	[ 209 ] 	= 207, -- Twilight Depths - Floor 2 	Micro 	Deepholm
	[ 372 ] 	= 371, -- Greenstone Quarry - Upper Quarry 	Micro 	The Jade Forest
	[ 373 ] 	= 371, -- Greenstone Quarry - Lower Quarry 	Micro 	The Jade Forest
	[ 374 ] 	= 371, -- The Widow's Wail 	Micro 	The Jade Forest
	[ 375 ] 	= 371, -- Oona Kagu 	Micro 	The Jade Forest
	[ 377 ] 	= 376, -- Cavern of Endless Echoes 	Micro 	Valley of the Four Winds
	[ 380 ] 	= 379, -- Howlingwind Cavern 	Micro 	Kun-Lai Summit
	[ 381 ] 	= 379, -- Pranksters' Hollow 	Micro 	Kun-Lai Summit
	[ 382 ] 	= 379, -- Knucklethump Hole 	Micro 	Kun-Lai Summit
	[ 383 ] 	= 379, -- The Deeper - Upper Deep 	Micro 	Kun-Lai Summit
	[ 384 ] 	= 379, -- The Deeper - Lower Deep 	Micro 	Kun-Lai Summit
	[ 385 ] 	= 379, -- Tomb of Conquerors 	Micro 	Kun-Lai Summit
	[ 386 ] 	= 379, -- Ruins of Korune 	Micro 	Kun-Lai Summit
	[ 387 ] 	= 379, -- Ruins of Korune - Crypt of Korune 	Micro 	Kun-Lai Summit
	[ 389 ] 	= 388, -- Niuzao Temple 	Micro 	Townlong Steppes
	[ 391 ] 	= 390, -- Shrine of Two Moons - Hall of the Crescent Moon 	Micro 	Vale of Eternal Blossoms
	[ 392 ] 	= 390, -- Shrine of Two Moons - The Imperial Mercantile 	Micro 	Vale of Eternal Blossoms
	[ 393 ] 	= 390, -- Shrine of Seven Stars - The Emperor's Step 	Micro 	Vale of Eternal Blossoms
	[ 394 ] 	= 390, -- Shrine of Seven Stars - The Imperial Exchange 	Micro 	Vale of Eternal Blossoms
	[ 395 ] 	= 390, -- Guo-Lai Halls 	Micro 	Vale of Eternal Blossoms
	[ 396 ] 	= 390, -- Guo-Lai Halls - The Hall of the Serpent 	Micro 	Vale of Eternal Blossoms
	[ 419 ] 	= 418, -- Ruins of Ogudei - Alliance Excavation 	Micro 	Krasarang Wilds
	[ 420 ] 	= 418, -- Ruins of Ogudei 	Micro 	Krasarang Wilds
	[ 421 ] 	= 418, -- Ruins of Ogudei - Reliquary Incursion 	Micro 	Krasarang Wilds
	[ 426 ] 	= 37, -- Echo Ridge Mine 	Micro 	Elwynn Forest
	[ 428 ] 	= 27, -- Frostmane Hovel 	Micro 	Dun Morogh
	[ 434 ] 	= 379, -- The Ancient Passage 	Micro 	Kun-Lai Summit
	[ 464 ] 	= 1, -- Spitescale Cavern 	Micro 	Durotar
	[ 466 ] 	= 18, -- Night Web's Hollow 	Micro 	Tirisfal Glades
	[ 470 ] 	= 27, -- Frostmane Hold 	Micro 	Dun Morogh
	[ 505 ] 	= 504, -- Lightning Vein Mine 	Micro 	Isle of Thunder
	[ 506 ] 	= 504, -- The Swollen Vault 	Micro 	Isle of Thunder
	[ 517 ] 	= 504, -- Lightning Vein Mine 	Micro 	Isle of Thunder
	[ 526 ] 	= 525, -- Turgall's Den - Bladespire Citadel 	Micro 	Frostfire Ridge
	[ 527 ] 	= 525, -- Turgall's Den - Bladespire Courtyard 	Micro 	Frostfire Ridge
	[ 528 ] 	= 525, -- Turgall's Den - Bladespire Throne 	Micro 	Frostfire Ridge
	[ 529 ] 	= 525, -- Turgall's Den - Sootstained Mines 	Micro 	Frostfire Ridge
	[ 530 ] 	= 525, -- Grom'gar 	Micro 	Frostfire Ridge
	[ 531 ] 	= 525, -- Grulloc's Grotto 	Micro 	Frostfire Ridge
	[ 532 ] 	= 525, -- Grulloc's Grotto - Grulloc's Lair 	Micro 	Frostfire Ridge
	[ 533 ] 	= 525, -- Snowfall Alcove 	Micro 	Frostfire Ridge
	[ 536 ] 	= 535, -- Tomb of Lights 	Micro 	Talador
	[ 537 ] 	= 535, -- Tomb of Souls 	Micro 	Talador
	[ 538 ] 	= 535, -- The Breached Ossuary 	Micro 	Talador
	[ 540 ] 	= 539, -- Bloodthorn Cave 	Micro 	Shadowmoon Valley
	[ 541 ] 	= 539, -- Den of Secrets 	Micro 	Shadowmoon Valley
	[ 544 ] 	= 543, -- Moira's Reach - Moira's Bastion 	Micro 	Gorgrond
	[ 545 ] 	= 543, -- Moira's Reach - The Armory 	Micro 	Gorgrond
	[ 546 ] 	= 543, -- Fissure of Fury 	Micro 	Gorgrond
	[ 547 ] 	= 543, -- Fissure of Fury - Heart of Fury 	Micro 	Gorgrond
	[ 548 ] 	= 543, -- Cragplume Cauldron - Cragplume Crater 	Micro 	Gorgrond
	[ 549 ] 	= 543, -- Cragplume Cauldron - Cragplume Depths 	Micro 	Gorgrond
	[ 551 ] 	= 550, -- The Masters' Cavern 	Micro 	Nagrand
	[ 552 ] 	= 550, -- Stonecrag Gorge 	Micro 	Nagrand
	[ 553 ] 	= 550, -- Oshu'gun 	Micro 	Nagrand
	[ 555 ] 	= 554, -- Cavern of Lost Spirits 	Micro 	Timeless Isle
	[ 578 ] 	= 577, -- Umbral Halls 	Micro 	Tanaan Jungle
	[ 579 ] 	= 579, -- Lunarfall Excavation 	Micro 	Lunarfall
	[ 580 ] 	= 579, -- Lunarfall Excavation 	Micro 	Lunarfall
	[ 581 ] 	= 579, -- Lunarfall Excavation 	Micro 	Lunarfall
	[ 585 ] 	= 585, -- Frostwall Mine 	Micro 	Frostwall
	[ 586 ] 	= 585, -- Frostwall Mine 	Micro 	Frostwall
	[ 587 ] 	= 585, -- Frostwall Mine 	Micro 	Frostwall
	[ 589 ] 	= 588, -- Ashran Mine 	Micro 	Ashran
	[ 631 ] 	= 630, -- Nar'thalas Academy 	Micro 	Azsuna
	[ 632 ] 	= 630, -- Oceanus Cove 	Micro 	Azsuna
	[ 633 ] 	= 630, -- Temple of a Thousand Lights 	Micro 	Azsuna
	[ 635 ] 	= 634, -- Shield's Rest 	Micro 	Stormheim
	[ 636 ] 	= 634, -- Stormscale Cavern 	Micro 	Stormheim
	[ 637 ] 	= 634, -- Thorignir Refuge - Floor 1 	Micro 	Stormheim
	[ 638 ] 	= 634, -- Thorignir Refuge - Floor 2 	Micro 	Stormheim
	[ 639 ] 	= 634, -- Aggramar's Vault 	Micro 	Stormheim
	[ 640 ] 	= 634, -- Vault of Eyir 	Micro 	Stormheim
	[ 642 ] 	= 641, -- Darkpens 	Micro 	Val'sharah
	[ 643 ] 	= 641, -- Sleeper's Barrow - Lower Sleepers Barrow 	Micro 	Val'sharah
	[ 644 ] 	= 641, -- Sleeper's Barrow - Upper Sleepers Barrow 	Micro 	Val'sharah
	[ 647 ] 	= 124, -- Acherus: The Ebon Hold - The Heart of Acherus 	Micro 	Broken Isles
	[ 648 ] 	= 124, -- Acherus: The Ebon Hold - Hall of Command 	Micro 	Broken Isles
	[ 651 ] 	= 650, -- Bitestone Enclave 	Micro 	Highmountain
	[ 652 ] 	= 650, -- Thunder Totem 	Micro 	Highmountain
	[ 653 ] 	= 650, -- Cave of the Blood Trial 	Micro 	Highmountain
	[ 654 ] 	= 650, -- Mucksnout Den 	Micro 	Highmountain
	[ 655 ] 	= 650, -- Lifespring Cavern - Lifespring Lower Cavern 	Micro 	Highmountain
	[ 656 ] 	= 650, -- Lifespring Cavern - Lifespring Upper Cavern 	Micro 	Highmountain
	[ 657 ] 	= 650, -- Path of Huln - Floor 1 	Micro 	Highmountain
	[ 658 ] 	= 650, -- Path of Huln - Floor 2 	Micro 	Highmountain
	[ 659 ] 	= 650, -- Stonedark Grotto 	Micro 	Highmountain
	[ 660 ] 	= 650, -- Feltotem Caverns 	Micro 	Highmountain
	[ 673 ] 	= 672, -- Cryptic Hollow 	Micro 	Mardum, the Shattered Abyss
	[ 674 ] 	= 672, -- Soul Engine - Lower Soul Engine 	Micro 	Mardum, the Shattered Abyss
	[ 675 ] 	= 672, -- Soul Engine - Upper Soul Engine 	Micro 	Mardum, the Shattered Abyss
	[ 681 ] 	= 680, -- The Arcway Vaults 	Micro 	Suramar
	[ 682 ] 	= 680, -- Felsoul Hold 	Micro 	Suramar
	[ 683 ] 	= 680, -- The Arcway Vaults 	Micro 	Suramar
	[ 684 ] 	= 680, -- Shattered Locus - Temple of Fal'adora 	Micro 	Suramar
	[ 685 ] 	= 680, -- Shattered Locus - Falanaar Tunnels 	Micro 	Suramar
	[ 686 ] 	= 680, -- Elor'shan 	Micro 	Suramar
	[ 687 ] 	= 680, -- Kel'balor 	Micro 	Suramar
	[ 688 ] 	= 680, -- Ley Station Anora 	Micro 	Suramar
	[ 689 ] 	= 680, -- Ley Station Moonfall 	Micro 	Suramar
	[ 690 ] 	= 680, -- Ley Station Aethenar 	Micro 	Suramar
	[ 691 ] 	= 680, -- Nyell's Workshop 	Micro 	Suramar
	[ 692 ] 	= 680, -- Falanaar Arcway - Falanaar Tunnels 	Micro 	Suramar
	[ 693 ] 	= 680, -- Falanaar Arcway - Falanaar Tunnels 	Micro 	Suramar
	[ 729 ] 	= 207, -- Crumbling Depths 	Micro 	Deepholm
	[ 831 ] 	= 830, -- The Vindicaar - Upper Deck 	Micro 	Krokuun
	[ 832 ] 	= 830, -- The Vindicaar - Lower Deck 	Micro 	Krokuun
	[ 833 ] 	= 830, -- Nath'raxas Spire 	Micro 	Krokuun
	[ 883 ] 	= 882, -- The Vindicaar - Upper Deck 	Micro 	Mac'Aree
	[ 884 ] 	= 882, -- The Vindicaar - Lower Deck 	Micro 	Mac'Aree
	[ 886 ] 	= 885, -- The Vindicaar - Upper Deck 	Micro 	Antoran Wastes
	[ 887 ] 	= 885, -- The Vindicaar - Lower Deck 	Micro 	Antoran Wastes
	[ 1009 ] 	= 864, -- Atul'Aman 	Micro 	Vol'dun
	[ 1030 ] 	= 217, -- Greymane Manor - Main Floor 	Micro 	Ruins of Gilneas
	[ 1031 ] 	= 179, -- Greymane Manor - Upper Floor 	Micro 	Gilneas
	[ 1163 ] 	= 1165, -- Dazar'alor - The Great Seal 	Micro 	Dazar'alor
	[ 1164 ] 	= 1165, -- Dazar'alor - Hall of Chroniclers 	Micro 	Dazar'alor
	[ 1171 ] 	= 895, -- Gol Thovas - Lower Cave 	Micro 	Tiragarde Sound
	[ 1172 ] 	= 895, -- Gol Thovas - Upper Cave 	Micro 	Tiragarde Sound
	[ 1173 ] 	= 862, -- Rastakhan's Might - Upper Decks 	Micro 	Zuldazar
	[ 1174 ] 	= 862, -- Rastakhan's Might - Lower Decks 	Micro 	Zuldazar
	[ 1176 ] 	= 862, -- Breath Of Pa'ku - Upper Deck 	Micro 	Zuldazar
	[ 1179 ] 	= 942, -- Abyssal Melody - Upper Deck 	Micro 	Stormsong Valley
	[ 1180 ] 	= 942, -- Abyssal Melody - Lower Deck 	Micro 	Stormsong Valley
	[ 1184 ] 	= 895, -- Winterchill Mine - Lower Cave 	Micro 	Tiragarde Sound
	[ 1185 ] 	= 895, -- Winterchill Mine - Upper Cave 	Micro 	Tiragarde Sound
	},

	orphan  = {
	[ 86 ] 	= 85, -- Orgrimmar - Cleft of Shadow 	Orphan 	Orgrimmar
	[ 91 ] 	= 25, -- Alterac Valley 	Orphan 	Hillsbrad Foothills
	[ 92 ] 	= 10, -- Warsong Gulch 	Orphan 	Northern Barrens
	[ 93 ] 	= 14, -- Arathi Basin 	Orphan 	Arathi Highlands
	[ 112 ] 	= 109, -- Eye of the Storm 	Orphan 	Netherstorm
	[ 124 ] 	= 124, -- Plaguelands: The Scarlet Enclave 	Orphan 	Eastern Plaguelands
	[ 128 ] 	= 115, -- Strand of the Ancients 	Orphan 	Dragonblight
	[ 142 ] 	= 114, -- The Oculus 	Orphan 	Borean Tundra
	[ 153 ] 	= 121, -- Gundrak 	Orphan 	Zul'Drak
	[ 155 ] 	= 115, -- The Obsidian Sanctum 	Orphan 	Dragonblight
	[ 169 ] 	= 118, -- Isle of Conquest 	Orphan 	Icecrown
	[ 179 ] 	= 179, -- Gilneas 	Orphan 	Eastern Kingdoms
	[ 184 ] 	= 118, -- Pit of Saron 	Orphan 	Icecrown
	[ 200 ] 	= 115, -- The Ruby Sanctum 	Orphan 	Dragonblight
	[ 206 ] 	= 118, -- Twin Peaks 	Orphan 	Twilight Highlands
	[ 218 ] 	= 217, -- Ruins of Gilneas City 	Orphan 	Ruins of Gilneas
	[ 219 ] 	= 71, -- Zul'Farrak 	Orphan 	Tanaris
	[ 233 ] 	= 50, -- Zul'Gurub 	Orphan 	Northern Stranglethorn
	[ 234 ] 	= 69, -- Dire Maul 	Orphan 	Feralas
	[ 247 ] 	= 81, -- Ruins of Ahn'Qiraj 	Orphan 	Silithus
	[ 273 ] 	= 71, -- The Black Morass 	Orphan 	Caverns of Time
	[ 274 ] 	= 71, -- Old Hillsbrad Foothills 	Orphan 	Caverns of Time
	[ 275 ] 	= 179, -- The Battle for Gilneas 	Orphan 	Gilneas
	[ 277 ] 	= 249, -- Lost City of the Tol'vir 	Orphan 	Uldum
	[ 327 ] 	= 327, -- Ahn'Qiraj: The Fallen Kingdom 	Orphan 	Kalimdor
	[ 329 ] 	= 71, -- Hyjal Summit 	Orphan 	Caverns of Time
	[ 333 ] 	= 95, -- Zul'Aman 	Orphan 	Ghostlands
	[ 337 ] 	= 50, -- Zul'Gurub 	Orphan 	Northern Stranglethorn
	[ 338 ] 	= 198, -- Molten Front 	Orphan 	Mount Hyjal
	[ 378 ] 	= 378, -- The Wandering Isle 	Orphan 	Azeroth
	[ 397 ] 	= 109, -- Eye of the Storm 	Orphan 	Netherstorm
	[ 398 ] 	= 71, -- Well of Eternity 	Orphan 	Tanaris
	[ 416 ] 	= 70, -- Dustwallow Marsh 	Orphan 	Dustwallow Marsh
	[ 417 ] 	= 390, -- Temple of Kotmogu 	Orphan 	Vale of Eternal Blossoms
	[ 427 ] 	= 27, -- Coldridge Valley 	Orphan 	Dun Morogh
	[ 447 ] 	= 371, -- A Brewing Storm 	Orphan 	The Jade Forest
	[ 448 ] 	= 371, -- The Jade Forest 	Orphan 	The Jade Forest
	[ 449 ] 	= 390, -- Temple of Kotmogu 	Orphan 	Vale of Eternal Blossoms
	[ 450 ] 	= 418, -- Unga Ingoo 	Orphan 	Krasarang Wilds
	[ 451 ] 	= 422, -- Assault on Zan'vess 	Orphan 	Dread Wastes
	[ 452 ] 	= 379, -- Brewmoon Festival 	Orphan 	Kun-Lai Summit
	[ 456 ] 	= 433, -- Terrace of Endless Spring 	Orphan 	The Veiled Stair
	[ 483 ] 	= 70, -- Dustwallow Marsh 	Orphan 	Dustwallow Marsh
	[ 486 ] 	= 418, -- Krasarang Wilds 	Orphan 	Krasarang Wilds
	[ 487 ] 	= 418, -- A Little Patience 	Orphan 	Krasarang Wilds
	[ 488 ] 	= 433, -- Dagger in the Dark 	Orphan 	The Veiled Stair
	[ 498 ] 	= 418, -- Krasarang Wilds 	Orphan 	Krasarang Wilds
	[ 516 ] 	= 504, -- Isle of Thunder 	Orphan 	Pandaria
	[ 519 ] 	= 376, -- Deepwind Gorge 	Orphan 	Valley of the Four Winds
	[ 520 ] 	= 390, -- Vale of Eternal Blossoms 	Orphan 	Vale of Eternal Blossoms
	[ 523 ] 	= 27, -- Dun Morogh 	Orphan 	Dun Morogh
	[ 524 ] 	= 524, -- Battle on the High Seas 	Orphan 	Kalimdor
	[ 571 ] 	= 554, -- Celestial Tournament 	Orphan 	Timeless Isle
	[ 577 ] 	= 534, -- Tanaan Jungle 	Orphan 	Draenor
	[ 582 ] 	= 539, -- Lunarfall 	Orphan 	Shadowmoon Valley
	[ 590 ] 	= 525, -- Frostwall 	Orphan 	Frostfire Ridge
	[ 594 ] 	= 535, -- Shattrath City 	Orphan 	Talador
	[ 622 ] 	= 588, -- Stormshield 	Orphan 	Ashran
	[ 623 ] 	= 25, -- Hillsbrad Foothills (Southshore vs. Tarren Mill) 	Orphan 	Hillsbrad Foothills
	[ 624 ] 	= 588, -- Warspear 	Orphan 	Ashran
	[ 645 ] 	= 645, -- Twisting Nether 	Orphan 	Broken Isles
	[ 649 ] 	= 634, -- Helheim 	Orphan 	Stormheim
	[ 671 ] 	= 634, -- The Cove of Nashal 	Orphan 	Broken Isles
	[ 672 ] 	= 672, -- Mardum, the Shattered Abyss 	Orphan 	Broken Isles
	[ 676 ] 	= 646, -- Broken Shore 	Orphan 	Broken Isles
	[ 694 ] 	= 634, -- Helmouth Shallows 	Orphan 	Stormheim
	[ 696 ] 	= 634, -- Stormheim 	Orphan 	Broken Isles
	[ 697 ] 	= 76, -- Azshara 	Orphan 	Azshara
	[ 709 ] 	= 378, -- The Wandering Isle 	Orphan 	Broken Isles
	[ 713 ] 	= 630, -- Eye of Azshara 	Orphan 	Azsuna
	[ 714 ] 	= 714, -- Niskara 	Orphan 	Broken Isles
	[ 715 ] 	= 641, -- Emerald Dreamway 	Orphan 	The Dreamgrove
	[ 717 ] 	= 717, -- Dreadscar Rift 	Orphan 	Broken Isles
	[ 718 ] 	= 717, -- Dreadscar Rift 	Orphan 	Broken Isles
	[ 725 ] 	= 276, -- The Maelstrom 	Orphan 	The Maelstrom
	[ 726 ] 	= 276, -- The Maelstrom 	Orphan 	Broken Isles
	[ 728 ] 	= 433, -- Terrace of Endless Spring 	Orphan 	The Veiled Stair
	[ 731 ] 	= 650, -- Neltharion's Lair 	Orphan 	Highmountain
	[ 733 ] 	= 641, -- Darkheart Thicket 	Orphan 	Val'sharah
	[ 738 ] 	= 198, -- Firelands 	Orphan 	Mount Hyjal
	[ 747 ] 	= 641, -- The Dreamgrove 	Orphan 	Val'sharah
	[ 748 ] 	= 714, -- Niskara 	Orphan 	Broken 
	[ 757 ] 	= 116, -- Ursoc's Lair 	Orphan 	Grizzly Hills
	[ 758 ] 	= 641, -- Gloaming Reef 	Orphan 	Val'sharah
	[ 760 ] 	= 198, -- Malorne's Nightmare 	Orphan 	Mount Hyjal
	[ 773 ] 	= 244, -- Tol Barad 	Orphan 	Eastern Kingdoms
	[ 775 ] 	= 103, -- The Exodar 	Orphan 	Kalimdor
	[ 776 ] 	= 97, -- Azuremyst Isle 	Orphan 	Kalimdor
	[ 793 ] 	= 641, -- Black Rook Hold 	Orphan 	Val'sharah
	[ 799 ] 	= 114, -- The Oculus 	Orphan 	Borean Tundra
	[ 823 ] 	= 118, -- Pit of Saron 	Orphan 	Icecrown
	[ 824 ] 	= 824, -- Islands 	Orphan 	Azeroth
	[ 834 ] 	= 27, -- Coldridge Valley 	Orphan 	Dun Morogh
	[ 837 ] 	= 14, -- Arathi Basin 	Orphan 	Arathi Highlands
	[ 838 ] 	= 36, -- Battle for Blackrock Mountain 	Orphan 	Burning Steppes
	[ 843 ] 	= 379, -- Shado-Pan Showdown 	Orphan 	Kun-Lai Summit
	[ 844 ] 	= 14, -- Arathi Basin 	Orphan 	Arathi Highlands
	[ 858 ] 	= 646, -- Assault on Broken Shore 	Orphan 	Broken Isles
	[ 859 ] 	= 10, -- Warsong Gulch 	Orphan 	Northern Barrens
	[ 860 ] 	= 115, -- The Ruby Sanctum 	Orphan 	Dragonblight
	[ 861 ] 	= 672, -- Mardum, the Shattered Abyss 	Orphan 	Mardum, the Shattered Abyss
	[ 871 ] 	= 871, -- The Lost Glacier 	Orphan 	Northrend
	[ 877 ] 	= 634, -- Fields of the Eternal Hunt 	Orphan 	Stormheim
	[ 903 ] 	= 882, -- The Seat of the Triumvirate 	Orphan 	Mac'Aree
	[ 904 ] 	= 81, -- Silithus Brawl 	Orphan 	Silithus
	[ 906 ] 	= 14, -- Arathi Highlands 	Orphan 	Eastern Kingdoms
	[ 907 ] 	= 907, -- Seething Shore 	Orphan 	Kalimdor
	[ 908 ] 	= 18, -- Ruins of Lordaeron 	Orphan 	Eastern Kingdoms
	[ 921 ] 	= 921, -- Invasion Point: Aurinor 	Orphan 	Argus
	[ 922 ] 	= 922, -- Invasion Point: Bonich 	Orphan 	Argus
	[ 923 ] 	= 923, -- Invasion Point: Cen'gar 	Orphan 	Argus
	[ 924 ] 	= 924, -- Invasion Point: Naigtal 	Orphan 	Argus
	[ 925 ] 	= 925, -- Invasion Point: Sangua 	Orphan 	Argus
	[ 926 ] 	= 926, -- Invasion Point: Val 	Orphan 	Argus
	[ 927 ] 	= 927, -- Greater Invasion Point: Pit Lord Vilemus 	Orphan 	Argus
	[ 928 ] 	= 928, -- Greater Invasion Point: Mistress Alluradel 	Orphan 	Argus
	[ 929 ] 	= 929, -- Greater Invasion Point: Matron Folnuna 	Orphan 	Argus
	[ 930 ] 	= 930, -- Greater Invasion Point: Inquisitor Meto 	Orphan 	Argus
	[ 931 ] 	= 931, -- Greater Invasion Point: Sotanathor 	Orphan 	Argus
	[ 932 ] 	= 932, -- Greater Invasion Point: Occularus 	Orphan 	Argus
	[ 933 ] 	= 933, -- Forge of Aeons 	Orphan 	Draenor
	[ 938 ] 	= 179, -- Gilneas Island 	Orphan 	Azeroth
	[ 939 ] 	= 939, -- Tropical Isle 8.0 	Orphan 	Azeroth
	[ 943 ] 	= 14, -- Arathi Highlands 	Orphan 	Eastern Kingdoms
	[ 971 ] 	= 971, -- Telogrus Rift 	Orphan 	Broken Isles
	[ 972 ] 	= 971, -- Telogrus Rift 	Orphan 	Broken Isles
	[ 974 ] 	= 895, -- Tol Dagor 	Orphan 	Tiragarde Sound
	[ 981 ] 	= 981, -- Un'gol Ruins 	Orphan 	Azeroth
	[ 1012 ] 	= 84, -- Stormwind City 	Orphan 	Eastern Kingdoms
	[ 1013 ] 	= 84, -- The Stockade 	Orphan 	Eastern Kingdoms
	[ 1044 ] 	= 14, -- Arathi Highlands 	Orphan 	Eastern Kingdoms
	[ 1156 ] 	= 1156, -- The Great Sea 	Orphan 	Azeroth
	[ 1157 ] 	= 1157, -- The Great Sea 	Orphan 	Azeroth
	[ 1181 ] 	= 862, -- Zuldazar 	Orphan 	Zandalar
	[ 1203 ] 	= 62, -- Darkshore 	Orphan 	Kalimdor
	[ 1332 ] 	= 62, -- Darkshore 	Orphan 	Kalimdor
	[ 1338 ] 	= 62, -- Darkshore 	Orphan 	Kalimdor
	[ 1343 ] 	= 62, -- 8.1 Darkshore Outdoor Final Phase 	Orphan 	
	[ 1349 ] 	= 895, -- Tol Dagor 	Orphan 	Tiragarde Sound
	[ 1366 ] 	= 14, -- Arathi Basin 	Orphan 	
	[ 1383 ] 	= 14, -- Arathi Basin 	Orphan 	Arathi Highlands
	[ 1471 ] 	= 641, -- Emerald Dreamway 	Orphan 	The Dreamgrove
	[ 1472 ] 	= 650, -- The Dragon's Spine 	Orphan 	Highmountain
	[ 1474 ] 	= 276, -- The Maelstrom - Heart of Azeroth 	Orphan 	The Maelstrom
	[ 1475 ] 	= 641, -- The Emerald Dream 	Orphan 	The Dreamgrove
	[ 1479 ] 	= 556, -- Baine Rescue 	Orphan 	Siege of Orgrimmar
	},
}
	